FIND_PATH(PGPLOT_INCLUDE_DIR cpgplot.h)
FIND_LIBRARY(PGPLOT_LIBRARY NAMES cpgplot)

IF (PGPLOT_INCLUDE_DIR AND PGPLOT_LIBRARY)
  SET(PGPLOT_FOUND TRUE)
ENDIF (PGPLOT_INCLUDE_DIR AND PGPLOT_LIBRARY)

IF (PGPLOT_FOUND)
IF (NOT PGPLOT_FIND_QUIETLY)
  MESSAGE(STATUS "Found PGPLOT library: ${PGPLOT_LIBRARY}")
ENDIF (NOT PGPLOT_FIND_QUIETLY)
ELSE (PGPLOT_FOUND)
IF (PGPLOT_FIND_REQUIRED)
  MESSAGE(FATAL_ERROR "Could not find PGPLOT Library")
ENDIF (PGPLOT_FIND_REQUIRED)
ENDIF (PGPLOT_FOUND)

